from dotenv import load_dotenv
import os

load_dotenv()

DEEPSEEK_API_KEY = os.getenv("DEEP_SEEK_API_KEY")
STEP_FUN_API_KEY=os.getenv("STEP_FUN_API_KEY")
SILICON_FLOW_API_KEY=os.getenv("SILICON_FLOW_API_KEY")

# DRAFTING AGENTS
ACTOR_BASE_URL="https://api.deepseek.com"
ACTOR_MODEL="deepseek-chat"
ACTOR_API_KEY=DEEPSEEK_API_KEY

INSTRUCTOR_BASE_URL="https://api.deepseek.com"
INSTRUCTOR_MODEL="deepseek-chat"
INSTRUCTOR_API_KEY=DEEPSEEK_API_KEY

SUMMARY_AGENT_BASE_URL="https://api.deepseek.com"
SUMMARY_AGENT_MODEL="deepseek-chat"
SUMMARY_AGENT_API_KEY=DEEPSEEK_API_KEY

# INFORMATION AGENT
INFORMATION_AGENT_BASE_URL="https://api.deepseek.com"
INFORMATION_AGENT_MODEL="deepseek-chat"
INFORMATION_AGENT_API_KEY=DEEPSEEK_API_KEY

# SYNDROME AGENT
SYNDROME_AGENT_BASE_URL="https://api.deepseek.com"
SYNDROME_AGENT_MODEL="deepseek-chat"
SYNDROME_AGENT_API_KEY=DEEPSEEK_API_KEY
# SYNDROME_AGENT_BASE_URL="https://api.siliconflow.cn/v1"
# SYNDROME_AGENT_MODEL="moonshotai/Kimi-K2-Instruct"
# SYNDROME_AGENT_API_KEY=SILICON_FLOW_API_KEY

# PLAN AGENT
PLAN_AGENT_BASE_URL="https://api.deepseek.com"
PLAN_AGENT_MODEL="deepseek-chat"
PLAN_AGENT_API_KEY=DEEPSEEK_API_KEY

# RAG AGENT
RAG_AGENT_BASE_URL="https://api.deepseek.com"
RAG_AGENT_MODEL="deepseek-chat"
RAG_AGENT_API_KEY=DEEPSEEK_API_KEY

# REPORT AGENTS
REPORT_AGENT_BASE_URL="https://api.deepseek.com"
REPORT_AGENT_MODEL="deepseek-chat"
REPORT_AGENT_API_KEY=DEEPSEEK_API_KEY

LINKS_AGENT_BASE_URL="https://api.deepseek.com"
LINKS_AGENT_MODEL="deepseek-chat"
LINKS_AGENT_API_KEY=DEEPSEEK_API_KEY

# TONGUE COATING AGENT
# QWENVL
TONGUE_COATING_AGENT_BASE_URL_MLLM="https://api.siliconflow.cn/v1"
TONGUE_COATING_AGENT_BASE_URL_LLM="https://api.deepseek.com"
TONGUE_COATING_AGENT_MODEL_MLLM="Qwen/Qwen2.5-VL-72B-Instruct"
TONGUE_COATING_AGENT_MODEL_LLM="deepseek-chat"
TONGUE_COATING_AGENT_API_KEY_MLLM=SILICON_FLOW_API_KEY
TONGUE_COATING_AGENT_API_KEY_LLM=DEEPSEEK_API_KEY

# TONGUE_COATING_AGENT_BASE_URL="https://api.stepfun.com/v1"
# TONGUE_COATING_AGENT_MODEL="step-1o-turbo-vision"
# TONGUE_COATING_AGENT_API_KEY=STEP_FUN_API_KEY








